import { CustomerInputProps } from "@/types/CustomerType";
import { GlobalInputProps } from "@/types/GlobalType";

export const customerData: CustomerInputProps = {
  id: 0,
  name: "",
  username: "",
  email: "",
  phone: "",
  address: "",
  description: "",
  firstname: "",
  lastname: "",
  birthday: "",
  genderId: 0,
  civil_StatusId: 0,
  nationality: 0,
  mobile: "",
  telp: "",
  fax: "",
  cityId: 0,
  stateId: 0,
  countryId: 0,
  districtId: 0,
  zipCodeId: 0,
  companyName: "",
  companyAddress: "",
  companyCityId: 0,
  companyStateId: 0,
  companyContryId: 0,
  companyZipCodeId: 0,
  membership_typeId: 0,
  alternativeCustomerId: "",
  cashierId: 0,
  startDate: "",
  expiryDate: "",
  taxNumber: "",
  notes: "",
  status: "",
  userId: 0,
  createdAt: "",
  updatedAt: "",
};

export const globalData: GlobalInputProps = {
  id: 0,
  name: "",
  username: "",
  email: "",
  phone: "",
  address: "",
  description: "",
  firstname: "",
  lastname: "",
  birthday: "",
  genderId: 0,
  civil_StatusId: 0,
  nationality: 0,
  mobile: "",
  telp: "",
  fax: "",
  cityId: 0,
  stateId: 0,
  countryId: 0,
  districtId: 0,
  zipCodeId: 0,
  companyName: "",
  companyAddress: "",
  companyCityId: 0,
  companyStateId: 0,
  companyContryId: 0,
  companyZipCodeId: 0,
  membership_typeId: 0,
  alternativeCustomerId: "",
  cashierId: 0,
  startDate: "",
  expiryDate: "",
  taxNumber: "",
  notes: "",
  status: "",
  userId: 0,
  createdAt: "",
  updatedAt: "",
};
